name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build solution
      run: dotnet build --configuration Release

    - name: Install Playwright CLI
      run: dotnet tool install --global Microsoft.Playwright.CLI

    - name: Install Playwright browsers
      run: playwright install --with-deps

    # -------------------------
    # API TESTS
    # -------------------------
    - name: Run API tests
      run: dotnet test AutomationApp.ApiTests/AutomationApp.ApiTests.csproj --logger "trx;LogFileName=api-tests.trx" --logger "html;logfilename=api-report.html"

    - name: Upload API TRX results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: api-test-results-trx
        path: "**/api-tests.trx"

    - name: Upload API HTML report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: api-test-results-html
        path: "**/api-report.html"

    # -------------------------
    # UI TESTS 
    # -------------------------
    - name: Run UI tests
      if: always()
      run: dotnet test AutomationApp.UiTests/AutomationApp.UiTests.csproj --logger "trx;LogFileName=ui-tests.trx" --logger "html;logfilename=ui-report.html"

    - name: Upload UI TRX results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: ui-test-results-trx
        path: "**/ui-tests.trx"

    - name: Upload UI HTML report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: ui-test-results-html
        path: "**/ui-report.html"
