name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build solution
      run: dotnet build --configuration Release

    - name: Install Playwright CLI
      run: dotnet tool install --global Microsoft.Playwright.CLI

    - name: Install Playwright browsers
      run: playwright install --with-deps

    # -------------------------
    # API TESTS
    # -------------------------
    - name: Run API tests
      run: dotnet test AutomationApp.ApiTests/AutomationApp.ApiTests.csproj --logger "trx;LogFileName=api-tests.trx"

    # -------------------------
    # UI TESTS (always run)
    # -------------------------
    - name: Run UI tests
      if: always()
      run: dotnet test AutomationApp.UiTests/AutomationApp.UiTests.csproj --logger "trx;LogFileName=ui-tests.trx"

    # -------------------------
    # Generate Allure Report
    # -------------------------
    - name: Install Allure CLI
      if: always()
      run: npm install -g allure-commandline --save-dev

    - name: Generate Allure HTML report
      if: always()
      run: allure generate --clean

    - name: Upload Allure Report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: allure-report
        path: allure-report
